-- Seed additional daily questions (Week 3–6)
-- Run this in Supabase SQL Editor after 003-seed-daily-questions.sql
-- Covers 2026-04-28 through 2026-05-27
-- Already applied in production; kept here so new environments can seed the full calendar.

insert into public.daily_questions (question_text, category, active_date) values
('What''s a compliment you received years ago that you still remember?',
 'reflection', '2026-04-28'),
('What''s your go-to way to make someone feel included in a group?',
 'advice', '2026-04-29'),
('What''s something tiny that instantly improves your mood?',
 'icebreaker', '2026-04-30'),
('What''s a belief you used to hold strongly but changed your mind on?',
 'hot-take', '2026-05-01'),
('Who taught you something important without realizing it?',
 'gratitude', '2026-05-02'),
('If your week had a theme song, what would it be and why?',
 'hypothetical', '2026-05-03'),
('What''s one conversation you''ve been avoiding that might help you grow?',
 'connection', '2026-05-04'),
('What''s a skill you admire in friends and want to build in yourself?',
 'reflection', '2026-05-05'),
('What''s the best advice you''ve ever ignored?',
 'advice', '2026-05-06'),
('What''s something people usually misunderstand about you at first?',
 'icebreaker', '2026-05-07'),
('Hot take: vulnerability is hardest when...',
 'hot-take', '2026-05-08'),
('Who in your life makes ordinary moments feel meaningful?',
 'gratitude', '2026-05-09'),
('If you could relive one conversation to say one more thing, which would it be?',
 'hypothetical', '2026-05-10'),
('What''s one way you''ve seen community show up in real life recently?',
 'connection', '2026-05-11'),
('What''s a trait you''re actively trying to strengthen right now?',
 'reflection', '2026-05-12'),
('What advice would you give your younger self about making friends?',
 'advice', '2026-05-13'),
('What''s your favorite way to reset after a tough day?',
 'icebreaker', '2026-05-14'),
('Unpopular opinion: "being busy" is often code for...',
 'hot-take', '2026-05-15'),
('Who deserves a thank-you text from you today?',
 'gratitude', '2026-05-16'),
('If you could instantly understand one thing about other people, what would it be?',
 'hypothetical', '2026-05-17'),
('What''s a moment when someone really listened to you?',
 'connection', '2026-05-18'),
('What do you want to be known for by the people closest to you?',
 'reflection', '2026-05-19'),
('What''s one social risk that paid off for you?',
 'advice', '2026-05-20'),
('What''s a surprisingly good way to meet new people?',
 'icebreaker', '2026-05-21'),
('Hot take: most conflict comes from assumptions about...',
 'hot-take', '2026-05-22'),
('Who has quietly supported you in a way you never forgot?',
 'gratitude', '2026-05-23'),
('If you had to host a dinner for five people from your life, who''s invited?',
 'hypothetical', '2026-05-24'),
('What''s one question that always leads to deeper conversations for you?',
 'connection', '2026-05-25'),
('What''s a part of yourself you''ve learned to accept this year?',
 'reflection', '2026-05-26'),
('What''s one practical tip for building stronger friendships in adulthood?',
 'advice', '2026-05-27')
on conflict (active_date) do nothing;
