-- Seed daily questions: fill the gap + restock through mid-October
-- Run this in Supabase SQL Editor after 002/003/003b scripts
-- Covers 2026-05-28 through 2026-10-15 (141 days)
-- Safe to re-run: skips dates that already exist

insert into public.daily_questions (question_text, category, active_date) values
('What''s a summer memory that still makes you smile?',
 'icebreaker', '2026-05-28'),
('When do you feel most like yourself around other people?',
 'reflection', '2026-05-29'),
('What''s one friendship that got stronger because of distance?',
 'connection', '2026-05-30'),
('What''s the kindest thing a friend has done for you lately?',
 'advice', '2026-05-31'),
('Hot take: the best hangouts don''t need...',
 'hot-take', '2026-06-01'),
('Who always knows how to cheer you up?',
 'gratitude', '2026-06-02'),
('If you could plan a perfect Saturday with friends, what would it look like?',
 'hypothetical', '2026-06-03'),
('What''s something you''ve been meaning to tell someone?',
 'advice', '2026-06-04'),
('What''s a small ritual that helps you stay close with people you love?',
 'icebreaker', '2026-06-05'),
('What''s your favorite way to turn a stranger into a friend?',
 'reflection', '2026-06-06'),
('Unpopular opinion: group chats are great until...',
 'hot-take', '2026-06-07'),
('Who made you feel welcome in a room where you felt out of place?',
 'gratitude', '2026-06-08'),
('If you could send a thank-you note to one person from your past, who would it be?',
 'hypothetical', '2026-06-09'),
('What''s a conversation that changed how you see the world?',
 'reflection', '2026-06-10'),
('What''s one habit that helps you show up better for your friends?',
 'connection', '2026-06-11'),
('What''s your go-to icebreaker that actually works?',
 'advice', '2026-06-12'),
('Hot take: quality time matters more than...',
 'hot-take', '2026-06-13'),
('Who in your life quietly leads by example?',
 'gratitude', '2026-06-14'),
('If loneliness had a cure that wasn''t a screen, what would it be?',
 'hypothetical', '2026-06-15'),
('What''s something you wish people asked you more often?',
 'advice', '2026-06-16'),
('What''s a boundary you set that improved a relationship?',
 'icebreaker', '2026-06-17'),
('What''s the best advice you''ve gotten about love or friendship?',
 'reflection', '2026-06-18'),
('What''s a song that always makes you want to call someone?',
 'connection', '2026-06-19'),
('Hot take: being a good friend starts with...',
 'hot-take', '2026-06-20'),
('Who taught you what loyalty looks like?',
 'gratitude', '2026-06-21'),
('If you could erase one awkward moment and redo it, which would it be?',
 'hypothetical', '2026-06-22'),
('What''s a recent moment of real connection that caught you off guard?',
 'connection', '2026-06-23'),
('What''s something you''re proud of about how you treat people?',
 'advice', '2026-06-24'),
('What''s one thing you do to make people feel seen?',
 'icebreaker', '2026-06-25'),
('What''s your favorite place to have a deep conversation?',
 'reflection', '2026-06-26'),
('Unpopular opinion: most people don''t need more friends — they need...',
 'hot-take', '2026-06-27'),
('Who showed up when you didn''t ask but really needed it?',
 'gratitude', '2026-06-28'),
('If you could host a campfire with anyone from your life, who''d get the first seat?',
 'hypothetical', '2026-06-29'),
('What''s a story you love telling about a friend?',
 'reflection', '2026-06-30'),
('What''s one fear that sometimes keeps you from reaching out?',
 'connection', '2026-07-01'),
('What''s a simple way you''ve rebuilt a friendship that faded?',
 'advice', '2026-07-02'),
('What''s something that always makes you feel less alone?',
 'icebreaker', '2026-07-03'),
('Hot take: phones should be put away when...',
 'hot-take', '2026-07-04'),
('Who deserves more of your attention this week?',
 'gratitude', '2026-07-05'),
('If you could ask your future self one question about relationships, what would it be?',
 'hypothetical', '2026-07-06'),
('What''s a compliment you wish you''d said out loud?',
 'icebreaker', '2026-07-07'),
('What''s one lesson friendship has taught you the hard way?',
 'reflection', '2026-07-08'),
('What''s your favorite tradition with the people closest to you?',
 'connection', '2026-07-09'),
('What''s the most underrated way to support a friend?',
 'advice', '2026-07-10'),
('Unpopular opinion: apologizing well means...',
 'hot-take', '2026-07-11'),
('Who makes you feel brave enough to be honest?',
 'gratitude', '2026-07-12'),
('If you could spend a day in someone else''s shoes, whose would you choose?',
 'hypothetical', '2026-07-13'),
('What''s a moment when you felt truly understood?',
 'advice', '2026-07-14'),
('What''s something you''re learning about yourself through community?',
 'icebreaker', '2026-07-15'),
('What''s one invitation you''ve been glad you said yes to?',
 'reflection', '2026-07-16'),
('What''s a question you wish someone would ask you tonight?',
 'connection', '2026-07-17'),
('Hot take: small talk is underrated because...',
 'hot-take', '2026-07-18'),
('Who has shaped the way you show up for others?',
 'gratitude', '2026-07-19'),
('If you could bottle one feeling from a great hangout, what would it be?',
 'hypothetical', '2026-07-20'),
('What''s a friendship milestone you''re celebrating quietly?',
 'connection', '2026-07-21'),
('What''s one way you''ve grown more open with people?',
 'advice', '2026-07-22'),
('What''s your favorite "just because" gesture for friends?',
 'icebreaker', '2026-07-23'),
('What''s something you do when you miss someone?',
 'reflection', '2026-07-24'),
('Unpopular opinion: the hardest part of adult friendship is...',
 'hot-take', '2026-07-25'),
('Who always makes ordinary plans feel special?',
 'gratitude', '2026-07-26'),
('If your closest friendships had a motto, what would it be?',
 'hypothetical', '2026-07-27'),
('What''s a hard truth a friend told you that helped you?',
 'reflection', '2026-07-28'),
('What''s one thing you want to be better at in relationships?',
 'connection', '2026-07-29'),
('What''s a place that always reminds you of someone you love?',
 'advice', '2026-07-30'),
('What''s the best "I''m thinking of you" message you''ve ever received?',
 'icebreaker', '2026-07-31'),
('Hot take: consistency beats grand gestures when...',
 'hot-take', '2026-08-01'),
('Who do you trust with the unfiltered version of your week?',
 'gratitude', '2026-08-02'),
('If you could invent a new holiday for friends, what would it celebrate?',
 'hypothetical', '2026-08-03'),
('What''s a conversation you keep coming back to in your mind?',
 'icebreaker', '2026-08-04'),
('What''s something you''ve stopped pretending about around friends?',
 'reflection', '2026-08-05'),
('What''s one way you make time for people even when life is loud?',
 'connection', '2026-08-06'),
('What''s your favorite unexpected friendship origin story?',
 'advice', '2026-08-07'),
('Unpopular opinion: "we should hang soon" usually means...',
 'hot-take', '2026-08-08'),
('Who helps you laugh at yourself in a good way?',
 'gratitude', '2026-08-09'),
('If you could fix one common misunderstanding between people, what would it be?',
 'hypothetical', '2026-08-10'),
('What''s a recent yes that led to a meaningful connection?',
 'advice', '2026-08-11'),
('What''s one value you won''t compromise on in friendships?',
 'icebreaker', '2026-08-12'),
('What''s a small act of care that means a lot to you?',
 'reflection', '2026-08-13'),
('What''s something you wish you''d known earlier about belonging?',
 'connection', '2026-08-14'),
('Hot take: listening well is rarer than...',
 'hot-take', '2026-08-15'),
('Who makes you feel at home even when you''re far from it?',
 'gratitude', '2026-08-16'),
('If you could replay one dinner conversation, which one and why?',
 'hypothetical', '2026-08-17'),
('What''s a way you''ve practiced courage in a relationship lately?',
 'connection', '2026-08-18'),
('What''s one thing you''re grateful your friends tolerate about you?',
 'advice', '2026-08-19'),
('What''s your favorite way to celebrate someone else''s win?',
 'icebreaker', '2026-08-20'),
('What''s a question that helped you get to know someone faster?',
 'reflection', '2026-08-21'),
('Unpopular opinion: loyalty doesn''t mean...',
 'hot-take', '2026-08-22'),
('Who reminds you of who you want to be?',
 'gratitude', '2026-08-23'),
('If kindness were a skill you could level up, what would you practice next?',
 'hypothetical', '2026-08-24'),
('What''s a moment when community surprised you in a good way?',
 'reflection', '2026-08-25'),
('What''s something you''re still figuring out about connecting with people?',
 'connection', '2026-08-26'),
('What''s one tradition you''d love to start with friends?',
 'advice', '2026-08-27'),
('What''s the most honest thing you''ve said to a friend recently?',
 'icebreaker', '2026-08-28'),
('Hot take: being present is harder than being...',
 'hot-take', '2026-08-29'),
('Who has your back in a way that still humbles you?',
 'gratitude', '2026-08-30'),
('If you could thank a teacher of connection from your past, who would it be?',
 'hypothetical', '2026-08-31'),
('What''s a story that always brings people closer when you share it?',
 'icebreaker', '2026-09-01'),
('What''s one fear you''ve outgrown in how you relate to others?',
 'reflection', '2026-09-02'),
('What''s a gentle way you''ve checked in on someone lately?',
 'connection', '2026-09-03'),
('What''s something that helps you feel grounded in a crowd?',
 'advice', '2026-09-04'),
('Unpopular opinion: alone time makes friendships better because...',
 'hot-take', '2026-09-05'),
('Who brings out your more playful side?',
 'gratitude', '2026-09-06'),
('If you could design the ideal first hangout with a new friend, what happens?',
 'hypothetical', '2026-09-07'),
('What''s a time you chose connection over convenience?',
 'advice', '2026-09-08'),
('What''s one thing you want your friends to know you''re working on?',
 'icebreaker', '2026-09-09'),
('What''s a comfort food that always tastes better with company?',
 'reflection', '2026-09-10'),
('What''s the best way someone has celebrated you?',
 'connection', '2026-09-11'),
('Hot take: real friends will tell you when...',
 'hot-take', '2026-09-12'),
('Who makes hard seasons feel more survivable?',
 'gratitude', '2026-09-13'),
('If you could write a short note to every friend you''ve ever had, what would it say?',
 'hypothetical', '2026-09-14'),
('What''s a conversation topic that always opens people up?',
 'connection', '2026-09-15'),
('What''s something you''ve learned by listening more than talking?',
 'advice', '2026-09-16'),
('What''s one way you protect the friendships that matter?',
 'icebreaker', '2026-09-17'),
('What''s your favorite "rainy day" activity with people you love?',
 'reflection', '2026-09-18'),
('Unpopular opinion: vulnerability without trust is...',
 'hot-take', '2026-09-19'),
('Who always remembers the little details about your life?',
 'gratitude', '2026-09-20'),
('If you could remove one obstacle to deeper friendships in your city, what would it be?',
 'hypothetical', '2026-09-21'),
('What''s a time someone''s patience with you meant everything?',
 'reflection', '2026-09-22'),
('What''s one relationship you''re intentionally investing in this season?',
 'connection', '2026-09-23'),
('What''s a phrase or question that helps you reconnect after time apart?',
 'advice', '2026-09-24'),
('What''s something beautiful about your community that outsiders might miss?',
 'icebreaker', '2026-09-25'),
('Hot take: belonging starts when someone...',
 'hot-take', '2026-09-26'),
('Who has modeled healthy conflict for you?',
 'gratitude', '2026-09-27'),
('If you could gift every friend one superpower, what would you choose?',
 'hypothetical', '2026-09-28'),
('What''s a memory that reminds you why friendship is worth the effort?',
 'icebreaker', '2026-09-29'),
('What''s one assumption about people you''ve had to unlearn?',
 'reflection', '2026-09-30'),
('What''s a small weekly habit that keeps you connected?',
 'connection', '2026-10-01'),
('What''s the most meaningful group experience you''ve been part of?',
 'advice', '2026-10-02'),
('Unpopular opinion: texting can''t replace...',
 'hot-take', '2026-10-03'),
('Who makes you feel safe enough to be messy?',
 'gratitude', '2026-10-04'),
('If tonight''s campfire could answer one question for you, what would you ask?',
 'hypothetical', '2026-10-05'),
('What''s a way you''ve extended grace to someone recently?',
 'advice', '2026-10-06'),
('What''s one thing you appreciate about how you make friends?',
 'icebreaker', '2026-10-07'),
('What''s a local spot that feels like a second living room?',
 'reflection', '2026-10-08'),
('What''s the best "welcome home" feeling you''ve ever gotten from people?',
 'connection', '2026-10-09'),
('Hot take: community isn''t found — it''s...',
 'hot-take', '2026-10-10'),
('Who do you hope never stops being part of your story?',
 'gratitude', '2026-10-11'),
('If you could host a monthly gathering, what would bring people back?',
 'hypothetical', '2026-10-12'),
('What''s a truth about connection that took you years to learn?',
 'connection', '2026-10-13'),
('What''s one way you''ve become easier to be close to?',
 'advice', '2026-10-14'),
('What''s a book, show, or song that helped you feel less alone?',
 'icebreaker', '2026-10-15')
on conflict (active_date) do nothing;
