-- Seed daily questions: restock through the end of 2026
-- Covers 2026-10-16 through 2026-12-31 (77 days)
-- Pinned nights: Halloween (Oct 31), Thanksgiving (Nov 26),
-- the longest night of the year (Dec 21), New Year's Eve (Dec 31)
-- Safe to re-run: skips dates that already exist

insert into public.daily_questions (question_text, category, active_date) values
('What''s the most "you" thing you did this week?',
 'icebreaker', '2026-10-16'),
('Hot take: the best nights out are the ones that...',
 'hot-take', '2026-10-17'),
('What''s something you''re pretending to be fine about?',
 'reflection', '2026-10-18'),
('Who would you text right now if it weren''t weird?',
 'connection', '2026-10-19'),
('You get one free day with zero obligations. What happens?',
 'hypothetical', '2026-10-20'),
('What''s something a friend said that you still think about?',
 'gratitude', '2026-10-21'),
('What''s the best advice you''ve gotten from someone younger than you?',
 'advice', '2026-10-22'),
('What''s your most controversial food opinion?',
 'icebreaker', '2026-10-23'),
('Unpopular opinion: people who are always early are...',
 'hot-take', '2026-10-24'),
('What did you want to be at 10 years old, and how close did you get?',
 'reflection', '2026-10-25'),
('What''s the last conversation that made you lose track of time?',
 'connection', '2026-10-26'),
('If you had to live in one decade forever, which one and why?',
 'hypothetical', '2026-10-27'),
('What''s a small thing someone did for you that they probably forgot?',
 'gratitude', '2026-10-28'),
('What''s a red flag you ignored and learned from?',
 'advice', '2026-10-29'),
('Who''s the friend you''d call if you needed bail money?',
 'icebreaker', '2026-10-30'),
('What actually scares you? Not spiders. The real answer.',
 'reflection', '2026-10-31'),
('Hot take: the group chat would fall apart without...',
 'hot-take', '2026-11-01'),
('Who do you owe a phone call?',
 'connection', '2026-11-02'),
('If you could swap lives with a friend for a week, whose would you pick?',
 'hypothetical', '2026-11-03'),
('Who''s a teacher, coach, or boss that changed your direction?',
 'gratitude', '2026-11-04'),
('What would you tell anyone starting their first real job?',
 'advice', '2026-11-05'),
('What''s a hill you will die on?',
 'icebreaker', '2026-11-06'),
('What''s a version of yourself you miss?',
 'reflection', '2026-11-07'),
('Unpopular opinion: Sunday is actually the worst day because...',
 'hot-take', '2026-11-08'),
('What''s the last thing you did alone that you wish someone was there for?',
 'connection', '2026-11-09'),
('You can call your 16-year-old self for 60 seconds. What do you say?',
 'hypothetical', '2026-11-10'),
('Who in your life gave something up so you could have more?',
 'gratitude', '2026-11-11'),
('How do you know when a friendship has run its course?',
 'advice', '2026-11-12'),
('What''s your go-to karaoke song, and have you actually sung it?',
 'icebreaker', '2026-11-13'),
('What are you quietly proud of that nobody knows about?',
 'reflection', '2026-11-14'),
('Hot take: the most attractive quality in a person is...',
 'hot-take', '2026-11-15'),
('When did you last feel lonely in a crowded room?',
 'connection', '2026-11-16'),
('If you won a million dollars, who''s the first person you''d tell?',
 'hypothetical', '2026-11-17'),
('What''s a place that shaped who you are?',
 'gratitude', '2026-11-18'),
('What''s one money lesson you learned the hard way?',
 'advice', '2026-11-19'),
('What''s the weirdest thing you''ve ever bonded with a stranger over?',
 'icebreaker', '2026-11-20'),
('What''s a decision you''re still not sure about?',
 'reflection', '2026-11-21'),
('Unpopular opinion: Thanksgiving food is...',
 'hot-take', '2026-11-22'),
('Who are you going home to this week, and how do you feel about it?',
 'connection', '2026-11-23'),
('You can add anyone to your Thanksgiving table. Who gets the seat?',
 'hypothetical', '2026-11-24'),
('How do you handle the relative who always starts something?',
 'advice', '2026-11-25'),
('What are you thankful for this year that you weren''t last year?',
 'gratitude', '2026-11-26'),
('What''s a family tradition that makes zero sense to outsiders?',
 'icebreaker', '2026-11-27'),
('What''s something about your family you only noticed once you left home?',
 'reflection', '2026-11-28'),
('Hot take: the hardest part of going home is...',
 'hot-take', '2026-11-29'),
('Who''s someone you drifted from that you''d like back?',
 'connection', '2026-11-30'),
('If this year was a movie, what''s the title?',
 'hypothetical', '2026-12-01'),
('What''s a stranger''s kindness from this year you still remember?',
 'gratitude', '2026-12-02'),
('What''s the best way you''ve found to say sorry?',
 'advice', '2026-12-03'),
('What''s a gift you got that you actually still use?',
 'icebreaker', '2026-12-04'),
('What''s a fear you walked straight into this year?',
 'reflection', '2026-12-05'),
('Unpopular opinion: the best part of the holidays is...',
 'hot-take', '2026-12-06'),
('Who would you want in your corner on your worst day?',
 'connection', '2026-12-07'),
('You can relive one day from this year. Which one?',
 'hypothetical', '2026-12-08'),
('Who made this year easier without being asked?',
 'gratitude', '2026-12-09'),
('What''s something you''d say no to more often if you could?',
 'advice', '2026-12-10'),
('What''s your most-played song this year? Be honest.',
 'icebreaker', '2026-12-11'),
('What''s something you believed in January that you don''t anymore?',
 'reflection', '2026-12-12'),
('Hot take: New Year''s resolutions are...',
 'hot-take', '2026-12-13'),
('What''s a friendship that surprised you this year?',
 'connection', '2026-12-14'),
('If you could give one person in your life a free week off, who would it be?',
 'hypothetical', '2026-12-15'),
('What''s the best thing someone taught you this year?',
 'gratitude', '2026-12-16'),
('What''s the advice you keep giving but never take?',
 'advice', '2026-12-17'),
('What''s the worst gift you''ve ever received?',
 'icebreaker', '2026-12-18'),
('When were you most yourself this year?',
 'reflection', '2026-12-19'),
('Unpopular opinion: holiday parties are...',
 'hot-take', '2026-12-20'),
('It''s the longest night of the year. Who do you wish was around the fire?',
 'connection', '2026-12-21'),
('What''s one gift you''d give yourself that money can''t buy?',
 'hypothetical', '2026-12-22'),
('How do you stay yourself around family during the holidays?',
 'advice', '2026-12-23'),
('What''s a holiday memory from when you were a kid that still feels warm?',
 'gratitude', '2026-12-24'),
('What''s been the best part of today so far?',
 'icebreaker', '2026-12-25'),
('What''s something you''re ready to leave in this year?',
 'reflection', '2026-12-26'),
('Hot take: the week between Christmas and New Year''s is...',
 'hot-take', '2026-12-27'),
('Who do you want to see more of next year?',
 'connection', '2026-12-28'),
('If next year had a theme, what would you want it to be?',
 'hypothetical', '2026-12-29'),
('What would you tell yourself on January 1st of this year?',
 'advice', '2026-12-30'),
('Who made this year worth it?',
 'gratitude', '2026-12-31')
on conflict (active_date) do nothing;
